# Generated by Django 5.1.2 on 2024-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('0', 'CARRINHO'), ('1', 'EMITIDA'), ('2', 'CANCELADA'), ('3', 'FINALIZADA')], default='P', max_length=1),
        ),
    ]
