# Generated by Django 5.1.2 on 2024-11-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
