# Generated by Django 4.2.16 on 2024-10-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='popularidade',
            field=models.IntegerField(default=0),
        ),
    ]
